
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.Random;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Maria
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        
        //Cambiamos el icono del jframe
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src"+File.separator+"Images"+File.separator+"logo.png"));
        
        //Se configura el timer para que "Click en Pikachu" parpadee cada medio segundo
        java.util.Timer timer = new java.util.Timer();
        timer.scheduleAtFixedRate(timerTask, 0,500);
    }
    
    TimerTask timerTask = new TimerTask(){
        public void run() {
            //Color c = Color.BLACK;
            String s = "<html><center>CLICK EN PIKACHU PARA COMENZAR</center></html>";
            Random rand = new Random();
            int x = rand.nextInt(2) + 1;
            switch (x) {
                case 2 : s = "";
            }

            jLabelClickEn.setText(s);
            jLabelClickEn2.setText(s);
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelClickEn = new javax.swing.JLabel();
        jLabelClickEn2 = new javax.swing.JLabel();
        jLabelEntrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(770, 459));
        setResizable(false);
        setSize(new java.awt.Dimension(770, 459));
        getContentPane().setLayout(null);

        jLabelClickEn.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabelClickEn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClickEn.setText("<html><center>CLICK EN PIKACHU PARA COMENZAR</center></html>");
        getContentPane().add(jLabelClickEn);
        jLabelClickEn.setBounds(60, 140, 130, 90);

        jLabelClickEn2.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabelClickEn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClickEn2.setText("<html><center>CLICK EN PIKACHU PARA COMENZAR</center></html>");
        getContentPane().add(jLabelClickEn2);
        jLabelClickEn2.setBounds(580, 140, 130, 90);

        jLabelEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEntrarMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelEntrar);
        jLabelEntrar.setBounds(400, 170, 110, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/portada.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 765, 430);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEntrarMouseClicked
        entrarJuego();
    }//GEN-LAST:event_jLabelEntrarMouseClicked

    public void entrarJuego()
    {
        Juego nuevoJuego = null;
        try {
            nuevoJuego = new Juego();
        } catch (MalformedURLException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        nuevoJuego.setVisible(true);
        dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelClickEn;
    private javax.swing.JLabel jLabelClickEn2;
    private javax.swing.JLabel jLabelEntrar;
    // End of variables declaration//GEN-END:variables
}
